"""crear_tablas_iniciales

Revision ID: 363612debbd8
Revises: 
Create Date: 2026-05-03 12:33:59.822527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363612debbd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicios',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('resetToken', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.Enum('CLIENTE', 'ENTRENADOR', 'ADMINISTRADOR', name='rolenum'), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('asistencias',
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horaResgistro', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clasesGrupales',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('entrenadorId', sa.Integer(), nullable=False),
    sa.Column('fechaHora', sa.DateTime(), nullable=False),
    sa.Column('cupoMaximo', sa.Integer(), nullable=False),
    sa.Column('cupoActual', sa.Integer(), nullable=False),
    sa.Column('inscripcionesAbiertas', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrenadorId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membresias',
    sa.Column('usuarioID', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MENSUAL', 'TRIMESTRAL', 'ANUAL', name='tipomembresiaenum'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACTIVA', 'VENCIDA', name='estadomembresiaenum'), nullable=False),
    sa.Column('fechaInicio', sa.Date(), nullable=True),
    sa.Column('fechaVencimiento', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioID'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutinas',
    sa.Column('clienteID', sa.Integer(), nullable=False),
    sa.Column('entrenadorID', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clienteID'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['entrenadorID'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejecuciones',
    sa.Column('rutinaId', sa.Integer(), nullable=False),
    sa.Column('EjercicioId', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipoMetrica', sa.Enum('REPETICIONES', 'TIEMPO', name='tipometricaenum'), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('duracionSeg', sa.Integer(), nullable=True),
    sa.Column('pesoKg', sa.Integer(), nullable=True),
    sa.Column('descansoSeg', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['EjercicioId'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['rutinaId'], ['rutinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('claseId', sa.Integer(), nullable=False),
    sa.Column('fechaInscripcion', sa.DateTime(), nullable=False),
    sa.Column('cancelada', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claseId'], ['clasesGrupales.id'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuarioId', 'claseId', name='uq_inscripcion_usuario_clase')
    )
    op.create_table('pagos',
    sa.Column('membresia_id', sa.Integer(), nullable=False),
    sa.Column('confirmado_por_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('comprobante_codigo', sa.String(length=50), nullable=True),
    sa.Column('metodoPago', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comprobante_codigo'),
    sa.UniqueConstraint('membresia_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('inscripciones')
    op.drop_table('ejecuciones')
    op.drop_table('rutinas')
    op.drop_table('membresias')
    op.drop_table('clasesGrupales')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('ejercicios')
    # ### end Alembic commands ###
